# Application & Environment Settings

spring:
  application:
    name: Mockify Backend

  profiles:
    default: local

  # Docker Configuration
  docker:
    compose:
      enabled: false

  # JPA & Hibernate Configuration
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Kolkata

  datasource:
    driver-class-name: org.postgresql.Driver

  jackson:
    time-zone: Asia/Kolkata

  # Database Migration (Flyway)
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  # OAuth 2 configuration (Google)
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            client-name: Google
            authorization-grant-type: authorization_code
        provider:
          google:
            issuer-uri: https://accounts.google.com

  # Email / SMTP Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

 # Redis configuration
  data:
    redis:
      host: redis
      port: 6379

# Application-Specific Properties (Frontend)
app:
  frontend:
    url: http://localhost:3000
    reset-password-url: http://localhost:3000/reset-password
  verification:
    email:
      ttl-minutes: 30
      frontend-url: http://localhost:3000/verify-email
  api-key:
    secret: ${API_KEY_SECRET}
    max-per-organization: ${API_KEY_MAX_PER_ORG:50}

# Cleanup Scheduling
cleanup:
  password-token:
    enabled: true
    cron: "0 0 * * * *"   # every hour

  mock-data:
    enabled: true
    cron: "0 */10 * * * *" # every 10 minutes

  invitations:
    enabled: true
    cron: "0 0 * * * *"   # top of every hour

# Actuator configuration
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: never


# Rate limiting configuration
mockify:
  rate-limit:

    # Global rate limit applied to all requests by default (Prevent bot spamming and DDOS)
    # If a request does not match any group below, this limit applies
    global:
      limit: 200
      window: 1m
      type: ip

    groups:

      # Very strict to prevent brute-force attacks
      auth:
        paths:
          - /api/auth/**
        limit: 5
        window: 1m
        type: ip

      public-mock:
        paths:
          - /api/mock/**
        limit: 200
        window: 1m
        type: ip

      lookup:
        paths:
          - /api/endpoints/lookup/**
        limit: 120
        window: 1m
        type: ip

      dashboard:
        paths:
          - /api/dashboard/**
        limit: 60
        window: 1m
        type: user

      organization:
        paths:
          - /api/organizations/**
        limit: 30
        window: 1m
        type: user

      project:
        paths:
          - /api/*/*
          - /api/*/projects/**
        limit: 40
        window: 1m
        type: user

      schema:
        paths:
          - /api/*/*/schemas
          - /api/*/*/schemas/**
        limit: 40
        window: 1m
        type: user

      records:
        paths:
          - /api/*/*/*/records/**
        limit: 60
        window: 1m
        type: user

      templates:
        paths:
          - /api/schema-templates/**
        limit: 20
        window: 1m
        type: user

      admin:
        paths:
          - /api/admin/**
        limit: 50
        window: 1m
        type: user

      actuator:
        paths:
          - /actuator/**
        limit: 30
        window: 1m
        type: ip